name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Check package.json
        run: cat package.json

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          REACT_APP_GOOGLE_CLIENT_ID: 771489989549-di3h0cglt71ed7hmgtknksm3ks0afdtj.apps.googleusercontent.com
          CI: false

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
